# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# .github/workflows/heroku-deploy.yml
jobs:
  heroku-deploy:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ 25a4f081-115a-4f10-b86d-44279c119623 }}
          heroku_app_name: ${{ HEROKU_APP_JAVA_CALCULATOR }}
          heroku_email: ${{ ndoumouandre@gmail.com }}
